services:
  - type: web
    name: vetsupport-ai-bot
    env: python
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://vetsupportai-1.onrender.com
      - key: WEBHOOK_SECRET
        value: vetsupport_webhook_secret
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    
  - type: pserv
    name: vetsupport-postgres
    plan: starter
    env: postgresql
    disk:
      name: vetsupport-db
      size: 1GB
